# Usa la imagen base de Debian
FROM debian:latest

# Información del autor
LABEL maintainer="hola@example.com"

ENV CLAVE=VALOR

run apt-get update -y && apt-get upgrade -y > $HOME/logs

COPY LEEME /root/LEEME

ADD 

# Mantén el contenedor activo
CMD ["tail", "-f", "/dev/null"]
